version: "3"
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgres
    env_file:
      - prod.env
    ports:
      - "5432:5432"
  test-db:
    image: postgres
    restart: always
    env_file:
      - test.env
    ports:
      - "5433:5432"
volumes:
  db_data:
    driver: local